### ISSUE TITLE
Is Nuget planned for this?

### ISSUE THREAD

**Issue by smartmeter** [madelson/MedallionUtilities#1]
Hi, I like the equality op you developed, is nuget planned for this?

**Comment by madelson** [comment]
@smartmeter yes I am planning to release each of the projects in this solution as it's own NuGet package.

**Comment by madelson** [comment]
@smartmeter this is now available on NuGet (https://www.nuget.org/packages/MedallionCollections/)

**Comment by smartmeter** [comment]
:+1: awesome
