### ISSUE TITLE
MedallionRand does not support .NET Standard 2.0 for .NET 5

### ISSUE THREAD

**Issue by hikarunoryoma** [madelson/MedallionUtilities#7]
Could we add support for .NET Standard 2.0 for MedallionRandom?  Looks like only .NET Standard 1.3 or NET Framework 4.5.2 is targeted at the moment.

**Comment by madelson** [comment]
@hikarunoryoma I assume you closed this because .NET Standard 1.3 does work for .NET 5? Let me know if you're having issues!

**Comment by hikarunoryoma** [comment]
yep, I figured things out!
